version: '3.8'

services:
  app:
    build: .
    ports:
      - "2331:2331"  # Nginx üzerinden servisi çalıştır
    volumes:
      - .:/app
    environment:
      - NODE_ENV=production
    restart: unless-stopped
